const estados = {
	CREADO: 'CREADO',
	ACTUALIZADO: 'ACTUALIZADO',
	BORRADO: 'BORRADO',
	EXITO: 'EXITO',
	FRACASO: 'FRACASO',
	YA_EXISTE: '23505',
	CONEXION_FALLIDA: 'ECONNREFUSED',
	ERROR_DESCONOCIDO: 'ERROR_DESCONOCIDO'
};

module.exports = estados;
